/**
 * Bot-bridge — shared types
 *
 * The bot-bridge module lets users drive an opencode chat session from an
 * external messenger (Telegram first; Discord/Slack later). It lives inside
 * the existing sidecar process so it inherits sidecar-level secrets,
 * workspace registry, and opencode-lifecycle wiring.
 *
 * Design decisions (see project_bot_bridge.md memory for rationale):
 *   - per-workspace allowlist, persisted in <workDir>/.tagma/bot-bridge.json
 *   - multi-user supported within one workspace (allowlist is an array)
 *   - chat_id → workspace binding established by pairing; one chat ↔ one workspace
 *   - read-class tools auto-approve, write/exec-class wait for Telegram approval
 *   - no headless mode; sidecar exit takes the bridge offline
 */

// Canonical platform domain type. Telegram ships first; discord/slack land
// with their transports (transports/*.ts). transports/types.ts re-exports
// this so there is exactly one Platform union in the codebase.
export type Platform = 'telegram' | 'discord' | 'slack';

export interface PairCode {
  /** 6-digit numeric string, generated by the desktop UI for one workspace */
  code: string;
  /** Workspace key (absolute workDir) this code will bind a chat to */
  workspaceKey: string;
  /** Optional human label saved alongside the from_id once paired */
  label: string | null;
  /** Wall-clock ms when this code expires (120 s TTL) */
  expiresAt: number;
}

export interface AllowlistEntry {
  /**
   * Platform-native numeric sender id.
   *   - Telegram: msg.from.id (private DM) — never the chat_id, which can be
   *     a negative group id and is not stable across chat type changes.
   */
  fromId: string;
  /** Optional human-readable label (e.g. "alice", "ops-team") */
  label: string | null;
  /** ISO timestamp when this entry was added via /pair */
  pairedAt: string;
  /** Platform; for now always 'telegram' */
  platform: Platform;
  /**
   * How this sender became authorized. Absent means a legacy paired sender.
   * Manual entries are the ones that switch pairing into explicit-ID mode.
   */
  source?: 'manual' | 'pair' | 'slack-bind';
}

export interface ChatRoute {
  /**
   * Platform-native chat id where the bot will reply.
   *   - Telegram: msg.chat.id; for private DMs == from.id; for groups it's a
   *     stable negative integer. We bind chat→workspace at pair time.
   */
  chatId: string;
  /** 'private' (1:1 DM) or 'group' (multi-member). Affects render decisions. */
  kind: 'private' | 'group';
  /** ISO timestamp when this chat was bound to the workspace */
  pairedAt: string;
  /** Platform */
  platform: Platform;
  /**
   * opencode session this chat drives, persisted so the binding (and its
   * readable history) survives a restart instead of the bot spawning a fresh
   * anonymous session. Absent on pre-Module-2 manifests (loaded leniently).
   */
  sessionId?: string;
}

export interface BridgeManifest {
  version: 1;
  allowlist: AllowlistEntry[];
  chats: ChatRoute[];
}

export const EMPTY_MANIFEST: BridgeManifest = {
  version: 1,
  allowlist: [],
  chats: [],
};
