import { sameFilesystemPathCoordinate } from './filesystem-paths.js';

export interface ChatPipelineIntentCandidate {
  id: string;
  path: string;
  pipelineName: string | null;
  currentCanvas: boolean;
  sessionOwned: boolean;
  manualNewDraft: boolean;
}

// Intent routing is deliberately ordinary text generation. The wildcard
// denial keeps every model-facing filesystem/shell/task/structured-output
// tool off; the Host parses and validates the bounded JSON text itself.
export const TAGMA_PIPELINE_INTENT_CLASSIFIER_TOOLS = Object.freeze({
  '*': false,
});

const MAX_CLASSIFICATION_TEXT_BYTES = 16 * 1024;
const encoder = new TextEncoder();

export type ResolvedChatPipelineIntent =
  | { kind: 'discussion' }
  | { kind: 'diagnosis'; target: ChatPipelineIntentCandidate | null }
  | { kind: 'create' }
  | { kind: 'edit'; target: ChatPipelineIntentCandidate }
  | {
      kind: 'clarify';
      question: string;
      candidates: ChatPipelineIntentCandidate[];
    };

export interface ChatPipelineIntentClassificationPrompt {
  system: string;
  user: string;
  /** Host validation and in-band text descriptor; never provider-native structured output. */
  schema: Record<string, unknown>;
}

export type ChatPipelineIntentClassificationAttempt = 1 | 2;

export function buildChatPipelineIntentCandidates(
  entries: readonly { path: string; pipelineName: string | null }[],
  coordinates: {
    currentCanvasPath?: string | null;
    sessionOwnedPath?: string | null;
    manualNewDraftPath?: string | null;
  },
): ChatPipelineIntentCandidate[] {
  const unique = new Map<string, { path: string; pipelineName: string | null }>();
  for (const entry of entries) {
    const normalized = entry.path.replace(/\\/g, '/');
    const key =
      /^[A-Za-z]:\//.test(normalized) || normalized.startsWith('//')
        ? normalized.toLowerCase()
        : normalized;
    if (!unique.has(key)) unique.set(key, entry);
  }
  return [...unique.values()]
    .sort((left, right) => left.path.localeCompare(right.path))
    .map((entry, index) => ({
      id: `pipeline-${index + 1}`,
      path: entry.path,
      pipelineName: entry.pipelineName,
      currentCanvas: sameFilesystemPathCoordinate(entry.path, coordinates.currentCanvasPath),
      sessionOwned: sameFilesystemPathCoordinate(entry.path, coordinates.sessionOwnedPath),
      manualNewDraft: sameFilesystemPathCoordinate(entry.path, coordinates.manualNewDraftPath),
    }));
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function candidateById(
  candidates: readonly ChatPipelineIntentCandidate[],
  value: unknown,
): ChatPipelineIntentCandidate | null {
  if (value === null) return null;
  if (typeof value !== 'string') {
    throw new Error('The pipeline intent classifier returned an invalid target candidate.');
  }
  const candidate = candidates.find((item) => item.id === value);
  if (!candidate) {
    throw new Error(`The pipeline intent classifier selected an unknown Host pipeline candidate.`);
  }
  return candidate;
}

function nullableCandidateSchema(candidateIds: readonly string[]): Record<string, unknown> {
  if (candidateIds.length === 0) return { type: 'null' };
  return {
    anyOf: [{ type: 'string', enum: candidateIds }, { type: 'null' }],
  };
}

/**
 * Build the isolated semantic-routing request. Candidate ids are generated by
 * the Host; model-authored paths or names never become write authority.
 */
export function buildChatPipelineIntentClassificationPrompt(
  userText: string,
  candidates: readonly ChatPipelineIntentCandidate[],
  attempt: ChatPipelineIntentClassificationAttempt = 1,
): ChatPipelineIntentClassificationPrompt {
  const candidateIds = candidates.map((candidate) => candidate.id);
  const schema = {
    type: 'object',
    additionalProperties: false,
    required: ['kind', 'targetCandidateId', 'clarification', 'candidateIds'],
    properties: {
      kind: {
        type: 'string',
        enum: ['discussion', 'diagnosis', 'create', 'edit', 'clarify'],
      },
      targetCandidateId: nullableCandidateSchema(candidateIds),
      clarification: {
        anyOf: [{ type: 'string', minLength: 1, maxLength: 500 }, { type: 'null' }],
      },
      candidateIds: {
        type: 'array',
        uniqueItems: true,
        maxItems: candidateIds.length,
        items:
          candidateIds.length > 0 ? { type: 'string', enum: candidateIds } : { type: 'string' },
      },
    },
  };
  const exactShapes = [
    {
      kind: 'discussion',
      targetCandidateId: null,
      clarification: null,
      candidateIds: [],
    },
    {
      kind: 'diagnosis',
      targetCandidateId: null,
      clarification: null,
      candidateIds: [],
    },
    {
      kind: 'create',
      targetCandidateId: null,
      clarification: null,
      candidateIds: [],
    },
    ...(candidateIds.length > 0
      ? [
          {
            kind: 'edit',
            targetCandidateId: candidateIds[0],
            clarification: null,
            candidateIds: [],
          },
        ]
      : []),
    {
      kind: 'clarify',
      targetCandidateId: null,
      clarification: 'Ask one concise question.',
      candidateIds: [],
    },
  ].map((shape) => JSON.stringify(shape));
  const inventory = candidates
    .map(
      (candidate) =>
        `<pipeline id="${escapeXml(candidate.id)}" current-canvas="${String(candidate.currentCanvas)}" ` +
        `session-owned="${String(candidate.sessionOwned)}" manual-new-draft="${String(candidate.manualNewDraft)}">` +
        `<name>${escapeXml(candidate.pipelineName ?? '')}</name>` +
        `<path>${escapeXml(candidate.path)}</path>` +
        `</pipeline>`,
    )
    .join('\n');
  return {
    system: [
      'Classify one Tagma Chat request before any pipeline branch is allocated.',
      ...(attempt === 2
        ? [
            'This is bounded repair attempt 2 of 2 because the first response violated the output contract.',
          ]
        : []),
      'Return exactly one JSON object and no markdown, prose, or code fence.',
      'The object must have exactly kind, targetCandidateId, clarification, and candidateIds.',
      `Valid exact shapes are: ${exactShapes.join('; ')}.`,
      'Do not use tools or inspect files.',
      'Use discussion when no concrete pipeline needs inspection or mutation.',
      'Use diagnosis for read-only inspection, explanation, debugging, review, or why/how questions.',
      'Use create only when the user wants a new pipeline rather than changing an inventoried one.',
      'Use edit only for an explicit pipeline-file mutation and select exactly one Host candidate id.',
      'The session-owned pipeline is the conversation branch; the current-canvas pipeline is only the visible editor canvas.',
      'If create versus edit or the edit target is materially ambiguous, use clarify instead of guessing.',
      'Never return a path or pipeline name as targetCandidateId.',
    ].join(' '),
    user: [
      '<tagma-pipeline-intent-request>',
      '<inventory>',
      inventory,
      '</inventory>',
      '<host-output-schema>',
      escapeXml(JSON.stringify(schema)),
      '</host-output-schema>',
      `<request>${escapeXml(userText)}</request>`,
      '</tagma-pipeline-intent-request>',
    ].join('\n'),
    schema,
  };
}

/**
 * Parse the model's ordinary text result at the Host boundary. This is the
 * syntactic counterpart to `resolveChatPipelineIntentDecision`: it replaces
 * provider-native schema enforcement without weakening candidate authority.
 */
export function parseChatPipelineIntentClassificationText(
  text: string,
  candidates: readonly ChatPipelineIntentCandidate[],
): ResolvedChatPipelineIntent {
  if (
    typeof text !== 'string' ||
    text.length === 0 ||
    encoder.encode(text).byteLength > MAX_CLASSIFICATION_TEXT_BYTES
  ) {
    throw new Error('The pipeline intent classifier returned invalid bounded JSON text.');
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(text.trim());
  } catch {
    throw new Error('The pipeline intent classifier did not return exactly one JSON object.');
  }
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw new Error('The pipeline intent classifier JSON result is not an object.');
  }
  const result = parsed as Record<string, unknown>;
  const keys = Object.keys(result).sort();
  if (keys.join(',') !== 'candidateIds,clarification,kind,targetCandidateId') {
    throw new Error('The pipeline intent classifier returned missing or unknown fields.');
  }
  if (
    (result.targetCandidateId !== null && typeof result.targetCandidateId !== 'string') ||
    (result.clarification !== null && typeof result.clarification !== 'string') ||
    !Array.isArray(result.candidateIds) ||
    result.candidateIds.length > candidates.length ||
    result.candidateIds.some(
      (id) => typeof id !== 'string' || id.length === 0 || id.length > 256,
    ) ||
    new Set(result.candidateIds).size !== result.candidateIds.length
  ) {
    throw new Error('The pipeline intent classifier returned invalid field types or bounds.');
  }
  if (typeof result.targetCandidateId === 'string' && result.targetCandidateId.length > 256) {
    throw new Error('The pipeline intent classifier target exceeded its bound.');
  }
  const clarification = result.clarification;
  if (
    typeof clarification === 'string' &&
    (clarification.trim().length === 0 ||
      Array.from(clarification).length > 500 ||
      encoder.encode(clarification).byteLength > 2_000)
  ) {
    throw new Error('The pipeline intent classifier clarification exceeded its bound.');
  }
  if (result.kind === 'clarify') {
    if (result.targetCandidateId !== null || typeof clarification !== 'string') {
      throw new Error('A clarification classification has invalid fields.');
    }
  } else if (clarification !== null || result.candidateIds.length !== 0) {
    throw new Error('A non-clarification classification has invalid clarification fields.');
  }
  return resolveChatPipelineIntentDecision(result, candidates);
}

/** Resolve and fail-close an already parsed classification decision. */
export function resolveChatPipelineIntentDecision(
  structured: unknown,
  candidates: readonly ChatPipelineIntentCandidate[],
): ResolvedChatPipelineIntent {
  if (!structured || typeof structured !== 'object' || Array.isArray(structured)) {
    throw new Error('The pipeline intent classifier did not return a structured result.');
  }
  const result = structured as Record<string, unknown>;
  switch (result.kind) {
    case 'discussion':
      if (result.targetCandidateId !== null) {
        throw new Error('A discussion classification cannot select a pipeline target.');
      }
      return { kind: 'discussion' };
    case 'diagnosis':
      return { kind: 'diagnosis', target: candidateById(candidates, result.targetCandidateId) };
    case 'create':
      if (result.targetCandidateId !== null) {
        throw new Error('A create classification cannot reuse an inventoried pipeline target.');
      }
      return { kind: 'create' };
    case 'edit': {
      const target = candidateById(candidates, result.targetCandidateId);
      if (!target) throw new Error('An edit classification requires one Host pipeline candidate.');
      return { kind: 'edit', target };
    }
    case 'clarify': {
      if (typeof result.clarification !== 'string' || !result.clarification.trim()) {
        throw new Error('An ambiguous pipeline classification requires a clarification question.');
      }
      if (!Array.isArray(result.candidateIds)) {
        throw new Error('An ambiguous pipeline classification requires a candidate list.');
      }
      const selected = result.candidateIds.map((id) => candidateById(candidates, id));
      if (selected.some((candidate) => candidate === null)) {
        throw new Error('An ambiguous pipeline classification returned an empty candidate.');
      }
      return {
        kind: 'clarify',
        question: result.clarification.trim(),
        candidates: selected as ChatPipelineIntentCandidate[],
      };
    }
    default:
      throw new Error('The pipeline intent classifier returned an unknown intent kind.');
  }
}
