import { sameFilesystemPathCoordinate } from './filesystem-paths.js';

export interface ChatPipelineIntentCandidate {
  id: string;
  path: string;
  pipelineName: string | null;
  currentCanvas: boolean;
  sessionOwned: boolean;
  manualNewDraft: boolean;
}

// OpenCode 1.18.18 implements json_schema through this internal-only tool.
// The wildcard denial keeps every model-facing filesystem/shell/task tool off.
export const TAGMA_PIPELINE_INTENT_CLASSIFIER_TOOLS = Object.freeze({
  '*': false,
  StructuredOutput: true,
});

export type ResolvedChatPipelineIntent =
  | { kind: 'discussion' }
  | { kind: 'diagnosis'; target: ChatPipelineIntentCandidate | null }
  | { kind: 'create' }
  | { kind: 'edit'; target: ChatPipelineIntentCandidate }
  | {
      kind: 'clarify';
      question: string;
      candidates: ChatPipelineIntentCandidate[];
    };

export interface ChatPipelineIntentClassificationPrompt {
  system: string;
  user: string;
  schema: Record<string, unknown>;
}

export function buildChatPipelineIntentCandidates(
  entries: readonly { path: string; pipelineName: string | null }[],
  coordinates: {
    currentCanvasPath?: string | null;
    sessionOwnedPath?: string | null;
    manualNewDraftPath?: string | null;
  },
): ChatPipelineIntentCandidate[] {
  const unique = new Map<string, { path: string; pipelineName: string | null }>();
  for (const entry of entries) {
    const normalized = entry.path.replace(/\\/g, '/');
    const key =
      /^[A-Za-z]:\//.test(normalized) || normalized.startsWith('//')
        ? normalized.toLowerCase()
        : normalized;
    if (!unique.has(key)) unique.set(key, entry);
  }
  return [...unique.values()]
    .sort((left, right) => left.path.localeCompare(right.path))
    .map((entry, index) => ({
      id: `pipeline-${index + 1}`,
      path: entry.path,
      pipelineName: entry.pipelineName,
      currentCanvas: sameFilesystemPathCoordinate(entry.path, coordinates.currentCanvasPath),
      sessionOwned: sameFilesystemPathCoordinate(entry.path, coordinates.sessionOwnedPath),
      manualNewDraft: sameFilesystemPathCoordinate(entry.path, coordinates.manualNewDraftPath),
    }));
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function candidateById(
  candidates: readonly ChatPipelineIntentCandidate[],
  value: unknown,
): ChatPipelineIntentCandidate | null {
  if (value === null) return null;
  if (typeof value !== 'string') {
    throw new Error('The pipeline intent classifier returned an invalid target candidate.');
  }
  const candidate = candidates.find((item) => item.id === value);
  if (!candidate) {
    throw new Error(`The pipeline intent classifier selected an unknown Host pipeline candidate.`);
  }
  return candidate;
}

function nullableCandidateSchema(candidateIds: readonly string[]): Record<string, unknown> {
  if (candidateIds.length === 0) return { type: 'null' };
  return {
    anyOf: [{ type: 'string', enum: candidateIds }, { type: 'null' }],
  };
}

/**
 * Build the isolated semantic-routing request. Candidate ids are generated by
 * the Host; model-authored paths or names never become write authority.
 */
export function buildChatPipelineIntentClassificationPrompt(
  userText: string,
  candidates: readonly ChatPipelineIntentCandidate[],
): ChatPipelineIntentClassificationPrompt {
  const candidateIds = candidates.map((candidate) => candidate.id);
  const inventory = candidates
    .map(
      (candidate) =>
        `<pipeline id="${escapeXml(candidate.id)}" current-canvas="${String(candidate.currentCanvas)}" ` +
        `session-owned="${String(candidate.sessionOwned)}" manual-new-draft="${String(candidate.manualNewDraft)}">` +
        `<name>${escapeXml(candidate.pipelineName ?? '')}</name>` +
        `<path>${escapeXml(candidate.path)}</path>` +
        `</pipeline>`,
    )
    .join('\n');
  return {
    system: [
      'Classify one Tagma Chat request before any pipeline branch is allocated.',
      'Return only the supplied JSON schema. Do not use tools or inspect files.',
      'Use discussion when no concrete pipeline needs inspection or mutation.',
      'Use diagnosis for read-only inspection, explanation, debugging, review, or why/how questions.',
      'Use create only when the user wants a new pipeline rather than changing an inventoried one.',
      'Use edit only for an explicit pipeline-file mutation and select exactly one Host candidate id.',
      'The session-owned pipeline is the conversation branch; the current-canvas pipeline is only the visible editor canvas.',
      'If create versus edit or the edit target is materially ambiguous, use clarify instead of guessing.',
      'Never return a path or pipeline name as targetCandidateId.',
    ].join(' '),
    user: [
      '<tagma-pipeline-intent-request>',
      '<inventory>',
      inventory,
      '</inventory>',
      `<request>${escapeXml(userText)}</request>`,
      '</tagma-pipeline-intent-request>',
    ].join('\n'),
    schema: {
      type: 'object',
      additionalProperties: false,
      required: ['kind', 'targetCandidateId', 'clarification', 'candidateIds'],
      properties: {
        kind: {
          type: 'string',
          enum: ['discussion', 'diagnosis', 'create', 'edit', 'clarify'],
        },
        targetCandidateId: nullableCandidateSchema(candidateIds),
        clarification: {
          anyOf: [{ type: 'string', minLength: 1, maxLength: 500 }, { type: 'null' }],
        },
        candidateIds: {
          type: 'array',
          uniqueItems: true,
          maxItems: candidateIds.length,
          items:
            candidateIds.length > 0 ? { type: 'string', enum: candidateIds } : { type: 'string' },
        },
      },
    },
  };
}

/** Resolve and fail-close the model's schema-constrained classification. */
export function resolveStructuredChatPipelineIntent(
  structured: unknown,
  candidates: readonly ChatPipelineIntentCandidate[],
): ResolvedChatPipelineIntent {
  if (!structured || typeof structured !== 'object' || Array.isArray(structured)) {
    throw new Error('The pipeline intent classifier did not return a structured result.');
  }
  const result = structured as Record<string, unknown>;
  switch (result.kind) {
    case 'discussion':
      if (result.targetCandidateId !== null) {
        throw new Error('A discussion classification cannot select a pipeline target.');
      }
      return { kind: 'discussion' };
    case 'diagnosis':
      return { kind: 'diagnosis', target: candidateById(candidates, result.targetCandidateId) };
    case 'create':
      if (result.targetCandidateId !== null) {
        throw new Error('A create classification cannot reuse an inventoried pipeline target.');
      }
      return { kind: 'create' };
    case 'edit': {
      const target = candidateById(candidates, result.targetCandidateId);
      if (!target) throw new Error('An edit classification requires one Host pipeline candidate.');
      return { kind: 'edit', target };
    }
    case 'clarify': {
      if (typeof result.clarification !== 'string' || !result.clarification.trim()) {
        throw new Error('An ambiguous pipeline classification requires a clarification question.');
      }
      if (!Array.isArray(result.candidateIds)) {
        throw new Error('An ambiguous pipeline classification requires a candidate list.');
      }
      const selected = result.candidateIds.map((id) => candidateById(candidates, id));
      if (selected.some((candidate) => candidate === null)) {
        throw new Error('An ambiguous pipeline classification returned an empty candidate.');
      }
      return {
        kind: 'clarify',
        question: result.clarification.trim(),
        candidates: selected as ChatPipelineIntentCandidate[],
      };
    }
    default:
      throw new Error('The pipeline intent classifier returned an unknown intent kind.');
  }
}
