import { describe, expect, test } from 'bun:test';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import {
  getRenderableMessageParts,
  shouldRenderMessageBubble,
} from '../src/components/chat/message-rendering';
import { MessageBubble } from '../src/components/chat/MessageBubble';
import type { OpencodeThreadEntry, Part, Provider, ToolState } from '../src/api/opencode-chat';
import { useChatStore } from '../src/store/chat-store';
import { inspectTaskToolCompletion } from '../src/utils/chat-tool-display';

type CompletedToolState = Extract<ToolState, { status: 'completed' }>;

function completedToolState(output: string): CompletedToolState {
  return {
    status: 'completed',
    input: {},
    output,
    title: 'Finished',
    metadata: {},
    time: { start: 1, end: 2 },
  } as CompletedToolState;
}

function toolEntry(tool: string, output: string): OpencodeThreadEntry {
  return {
    info: {
      id: `msg-${tool}`,
      role: 'assistant',
    },
    parts: [
      {
        id: `part-${tool}`,
        sessionID: 'session',
        messageID: `msg-${tool}`,
        type: 'tool',
        callID: `call-${tool}`,
        tool,
        state: {
          ...completedToolState(output),
          input: tool === 'task' ? { description: 'Build the pipeline' } : {},
        },
      },
    ],
  } as unknown as OpencodeThreadEntry;
}

describe('shouldRenderMessageBubble', () => {
  test('does not render assistant messages that only contain empty text parts', () => {
    const emptyTextPart = {
      id: 'part-empty',
      sessionID: 'session',
      messageID: 'message',
      type: 'text',
      text: '',
    } as Part;

    expect(
      shouldRenderMessageBubble({
        info: { role: 'assistant' },
        parts: [emptyTextPart],
      }),
    ).toBe(false);
    expect(getRenderableMessageParts([emptyTextPart])).toEqual([]);
  });

  test('keeps visible assistant text parts renderable', () => {
    const textPart = {
      id: 'part-text',
      sessionID: 'session',
      messageID: 'message',
      type: 'text',
      text: 'Done.',
    } as Part;

    expect(
      shouldRenderMessageBubble({
        info: { role: 'assistant' },
        parts: [textPart],
      }),
    ).toBe(true);
    expect(getRenderableMessageParts([textPart])).toEqual([textPart]);
  });

  test('renders assistant messages that only have footer error information', () => {
    expect(
      shouldRenderMessageBubble({
        info: {
          role: 'assistant',
          error: {
            name: 'MessageAbortedError',
            data: { message: 'aborted' },
          },
          cost: 0,
          tokens: {
            input: 0,
            output: 0,
            reasoning: 0,
            cache: { read: 0, write: 0 },
          },
        },
        parts: [] as Part[],
      }),
    ).toBe(true);
  });

  test('renders assistant messages that only have footer cost information', () => {
    const entry = {
      info: {
        id: 'msg-cost-only',
        role: 'assistant',
        cost: 0.012,
      },
      parts: [] as Part[],
    } as unknown as OpencodeThreadEntry;

    const html = renderToStaticMarkup(createElement(MessageBubble, { entry }));

    expect(html).toContain('$0.012');
    expect(html).toContain('output: 0');
  });
});

describe('assistant response controls', () => {
  test('renders copy action and provider/model attribution below assistant response', () => {
    const previousProviders = useChatStore.getState().providers;
    useChatStore.setState({
      providers: [
        {
          id: 'anthropic',
          name: 'Anthropic',
          models: {
            'claude-sonnet-4-5': {
              id: 'claude-sonnet-4-5',
              name: 'Claude Sonnet 4.5',
            },
          },
        } as unknown as Provider,
      ],
    });

    try {
      const entry = {
        info: {
          id: 'msg-assistant',
          role: 'assistant',
          providerID: 'anthropic',
          modelID: 'claude-sonnet-4-5',
        },
        parts: [
          {
            id: 'part-text',
            sessionID: 'session',
            messageID: 'msg-assistant',
            type: 'text',
            text: 'First line.\n\nSecond line.',
          },
        ],
      } as unknown as OpencodeThreadEntry;

      const html = renderToStaticMarkup(createElement(MessageBubble, { entry }));

      expect(html).toContain('First line.');
      expect(html).toContain('Copy assistant response');
      expect(html).toContain('Generated by');
      expect(html).toContain('Anthropic');
      expect(html).toContain('Claude Sonnet 4.5');
      expect(html.indexOf('Copy assistant response')).toBeGreaterThan(html.indexOf('First line.'));
      expect(html.indexOf('Generated by')).toBeGreaterThan(html.indexOf('First line.'));
    } finally {
      useChatStore.setState({ providers: previousProviders });
    }
  });

  test('assistant attribution tolerates provider entries before models are available', () => {
    const previousProviders = useChatStore.getState().providers;
    useChatStore.setState({
      providers: [
        {
          id: 'local',
          name: 'Local Provider',
        } as unknown as Provider,
      ],
    });

    try {
      const entry = {
        info: {
          id: 'msg-assistant-minimal-provider',
          role: 'assistant',
          providerID: 'local',
          modelID: 'llama3.1',
        },
        parts: [
          {
            id: 'part-text',
            sessionID: 'session',
            messageID: 'msg-assistant-minimal-provider',
            type: 'text',
            text: 'Done.',
          },
        ],
      } as unknown as OpencodeThreadEntry;

      const html = renderToStaticMarkup(createElement(MessageBubble, { entry }));

      expect(html).toContain('Local Provider');
      expect(html).toContain('llama3.1');
      expect(html).toContain('Copy assistant response');
    } finally {
      useChatStore.setState({ providers: previousProviders });
    }
  });
});

describe('user attachment references', () => {
  test('renders the persisted attachment label without exposing its hidden context', () => {
    const entry = {
      info: {
        id: 'msg-user-with-reference',
        role: 'user',
      },
      parts: [
        {
          id: 'part-user-with-reference',
          sessionID: 'session',
          messageID: 'msg-user-with-reference',
          type: 'text',
          text:
            '<ask-ai-context>\n' +
            '<attachment label="Run failed">\n' +
            'stderr tail\n' +
            '</attachment>\n' +
            '</ask-ai-context>\n\n' +
            'Fix this bug.',
        },
      ],
    } as unknown as OpencodeThreadEntry;

    const html = renderToStaticMarkup(createElement(MessageBubble, { entry }));

    expect(html).toContain('Run failed');
    expect(html).toContain('Fix this bug.');
    expect(html).not.toContain('stderr tail');
    expect(html).not.toContain('ask-ai-context');
  });

  test('keeps an attachment-only message visible without rendering an empty text bubble', () => {
    const entry = {
      info: {
        id: 'msg-user-reference-only',
        role: 'user',
      },
      parts: [
        {
          id: 'part-user-reference-only',
          sessionID: 'session',
          messageID: 'msg-user-reference-only',
          type: 'text',
          text:
            '<ask-ai-context>\n' +
            '<attachment label="Run failed">\n' +
            'stderr tail\n' +
            '</attachment>\n' +
            '</ask-ai-context>\n\n',
        },
      ],
    } as unknown as OpencodeThreadEntry;

    const html = renderToStaticMarkup(createElement(MessageBubble, { entry }));

    expect(html).toContain('Run failed');
    expect(html).not.toContain('stderr tail');
    expect(html).not.toContain('chat-user-bubble');
  });
});

describe('task tool completion presentation', () => {
  test('treats an empty task_result wrapper as no usable result', () => {
    const state = completedToolState('<task><task_result></task_result></task>');
    const rawOutput = state.output;

    expect(inspectTaskToolCompletion('task', state)).toEqual({ kind: 'no-usable-result' });
    expect(state.output).toBe(rawOutput);

    const html = renderToStaticMarkup(
      createElement(MessageBubble, { entry: toolEntry('task', state.output) }),
    );
    expect(html).toContain('no usable result');
    expect(html).toContain('Child task returned without a usable result.');
    expect(html).toContain('text-tagma-warning');
    expect(html).not.toContain('text-tagma-ready');
  });

  test('treats whitespace-only task_result as no usable result', () => {
    expect(inspectTaskToolCompletion('task', completedToolState(''))).toEqual({
      kind: 'no-usable-result',
    });
    expect(
      inspectTaskToolCompletion(
        'task',
        completedToolState('<task><task_result>\n  \t\n</task_result></task>'),
      ),
    ).toEqual({ kind: 'no-usable-result' });
  });

  test('presents a non-empty wrapped result as a neutral return', () => {
    const state = completedToolState('<task><task_result>Built pipeline.yml</task_result></task>');

    expect(inspectTaskToolCompletion('task', state)).toEqual({
      kind: 'returned',
      result: 'Built pipeline.yml',
    });

    const html = renderToStaticMarkup(
      createElement(MessageBubble, { entry: toolEntry('task', state.output) }),
    );
    expect(html).toContain('>returned</span>');
    expect(html).toContain('Built pipeline.yml');
    expect(html).not.toContain('text-tagma-ready');
  });

  test('fails closed for malformed task markup but accepts plain non-empty output', () => {
    expect(
      inspectTaskToolCompletion('task', completedToolState('<task><task_result>orphaned')),
    ).toEqual({ kind: 'no-usable-result' });
    expect(inspectTaskToolCompletion('task', completedToolState('Plain child response.'))).toEqual({
      kind: 'returned',
      result: 'Plain child response.',
    });
  });

  test('does not reinterpret completed status for non-task tools', () => {
    const state = completedToolState('Done.');
    expect(inspectTaskToolCompletion('read', state)).toBeNull();

    const html = renderToStaticMarkup(
      createElement(MessageBubble, { entry: toolEntry('read', state.output) }),
    );
    expect(html).toContain('>completed</span>');
    expect(html).toContain('text-tagma-ready');
    expect(html).not.toContain('no usable result');
  });
});
