import { describe, expect, test } from 'bun:test';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import {
  getRenderableMessageParts,
  shouldRenderMessageBubble,
} from '../src/components/chat/message-rendering';
import { MessageBubble } from '../src/components/chat/MessageBubble';
import type { OpencodeThreadEntry, Part, Provider } from '../src/api/opencode-chat';
import { useChatStore } from '../src/store/chat-store';

describe('shouldRenderMessageBubble', () => {
  test('does not render assistant messages that only contain empty text parts', () => {
    const emptyTextPart = {
      id: 'part-empty',
      sessionID: 'session',
      messageID: 'message',
      type: 'text',
      text: '',
    } as Part;

    expect(
      shouldRenderMessageBubble({
        info: { role: 'assistant' },
        parts: [emptyTextPart],
      }),
    ).toBe(false);
    expect(getRenderableMessageParts([emptyTextPart])).toEqual([]);
  });

  test('keeps visible assistant text parts renderable', () => {
    const textPart = {
      id: 'part-text',
      sessionID: 'session',
      messageID: 'message',
      type: 'text',
      text: 'Done.',
    } as Part;

    expect(
      shouldRenderMessageBubble({
        info: { role: 'assistant' },
        parts: [textPart],
      }),
    ).toBe(true);
    expect(getRenderableMessageParts([textPart])).toEqual([textPart]);
  });

  test('renders assistant messages that only have footer error information', () => {
    expect(
      shouldRenderMessageBubble({
        info: {
          role: 'assistant',
          error: {
            name: 'MessageAbortedError',
            data: { message: 'aborted' },
          },
          cost: 0,
          tokens: {
            input: 0,
            output: 0,
            reasoning: 0,
            cache: { read: 0, write: 0 },
          },
        },
        parts: [] as Part[],
      }),
    ).toBe(true);
  });

  test('renders assistant messages that only have footer cost information', () => {
    const entry = {
      info: {
        id: 'msg-cost-only',
        role: 'assistant',
        cost: 0.012,
      },
      parts: [] as Part[],
    } as unknown as OpencodeThreadEntry;

    const html = renderToStaticMarkup(createElement(MessageBubble, { entry }));

    expect(html).toContain('$0.012');
    expect(html).toContain('output: 0');
  });
});

describe('assistant response controls', () => {
  test('renders copy action and provider/model attribution below assistant response', () => {
    const previousProviders = useChatStore.getState().providers;
    useChatStore.setState({
      providers: [
        {
          id: 'anthropic',
          name: 'Anthropic',
          models: {
            'claude-sonnet-4-5': {
              id: 'claude-sonnet-4-5',
              name: 'Claude Sonnet 4.5',
            },
          },
        } as unknown as Provider,
      ],
    });

    try {
      const entry = {
        info: {
          id: 'msg-assistant',
          role: 'assistant',
          providerID: 'anthropic',
          modelID: 'claude-sonnet-4-5',
        },
        parts: [
          {
            id: 'part-text',
            sessionID: 'session',
            messageID: 'msg-assistant',
            type: 'text',
            text: 'First line.\n\nSecond line.',
          },
        ],
      } as unknown as OpencodeThreadEntry;

      const html = renderToStaticMarkup(createElement(MessageBubble, { entry }));

      expect(html).toContain('First line.');
      expect(html).toContain('Copy assistant response');
      expect(html).toContain('Generated by');
      expect(html).toContain('Anthropic');
      expect(html).toContain('Claude Sonnet 4.5');
      expect(html.indexOf('Copy assistant response')).toBeGreaterThan(html.indexOf('First line.'));
      expect(html.indexOf('Generated by')).toBeGreaterThan(html.indexOf('First line.'));
    } finally {
      useChatStore.setState({ providers: previousProviders });
    }
  });

  test('assistant attribution tolerates provider entries before models are available', () => {
    const previousProviders = useChatStore.getState().providers;
    useChatStore.setState({
      providers: [
        {
          id: 'local',
          name: 'Local Provider',
        } as unknown as Provider,
      ],
    });

    try {
      const entry = {
        info: {
          id: 'msg-assistant-minimal-provider',
          role: 'assistant',
          providerID: 'local',
          modelID: 'llama3.1',
        },
        parts: [
          {
            id: 'part-text',
            sessionID: 'session',
            messageID: 'msg-assistant-minimal-provider',
            type: 'text',
            text: 'Done.',
          },
        ],
      } as unknown as OpencodeThreadEntry;

      const html = renderToStaticMarkup(createElement(MessageBubble, { entry }));

      expect(html).toContain('Local Provider');
      expect(html).toContain('llama3.1');
      expect(html).toContain('Copy assistant response');
    } finally {
      useChatStore.setState({ providers: previousProviders });
    }
  });
});

describe('user attachment references', () => {
  test('renders the persisted attachment label without exposing its hidden context', () => {
    const entry = {
      info: {
        id: 'msg-user-with-reference',
        role: 'user',
      },
      parts: [
        {
          id: 'part-user-with-reference',
          sessionID: 'session',
          messageID: 'msg-user-with-reference',
          type: 'text',
          text:
            '<ask-ai-context>\n' +
            '<attachment label="Run failed">\n' +
            'stderr tail\n' +
            '</attachment>\n' +
            '</ask-ai-context>\n\n' +
            'Fix this bug.',
        },
      ],
    } as unknown as OpencodeThreadEntry;

    const html = renderToStaticMarkup(createElement(MessageBubble, { entry }));

    expect(html).toContain('Run failed');
    expect(html).toContain('Fix this bug.');
    expect(html).not.toContain('stderr tail');
    expect(html).not.toContain('ask-ai-context');
  });

  test('keeps an attachment-only message visible without rendering an empty text bubble', () => {
    const entry = {
      info: {
        id: 'msg-user-reference-only',
        role: 'user',
      },
      parts: [
        {
          id: 'part-user-reference-only',
          sessionID: 'session',
          messageID: 'msg-user-reference-only',
          type: 'text',
          text:
            '<ask-ai-context>\n' +
            '<attachment label="Run failed">\n' +
            'stderr tail\n' +
            '</attachment>\n' +
            '</ask-ai-context>\n\n',
        },
      ],
    } as unknown as OpencodeThreadEntry;

    const html = renderToStaticMarkup(createElement(MessageBubble, { entry }));

    expect(html).toContain('Run failed');
    expect(html).not.toContain('stderr tail');
    expect(html).not.toContain('border-tagma-ready/40');
  });
});
