import { describe, expect, test } from 'bun:test';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import {
  getRenderableMessageParts,
  shouldRenderMessageBubble,
} from '../src/components/chat/message-rendering';
import { MessageBubble } from '../src/components/chat/MessageBubble';
import type { OpencodeThreadEntry, Part, Provider } from '../src/api/opencode-chat';
import { useChatStore } from '../src/store/chat-store';

describe('shouldRenderMessageBubble', () => {
  test('does not render assistant messages that only contain empty text parts', () => {
    const emptyTextPart = {
      id: 'part-empty',
      sessionID: 'session',
      messageID: 'message',
      type: 'text',
      text: '',
    } as Part;

    expect(
      shouldRenderMessageBubble({
        info: { role: 'assistant' },
        parts: [emptyTextPart],
      }),
    ).toBe(false);
    expect(getRenderableMessageParts([emptyTextPart])).toEqual([]);
  });

  test('keeps visible assistant text parts renderable', () => {
    const textPart = {
      id: 'part-text',
      sessionID: 'session',
      messageID: 'message',
      type: 'text',
      text: 'Done.',
    } as Part;

    expect(
      shouldRenderMessageBubble({
        info: { role: 'assistant' },
        parts: [textPart],
      }),
    ).toBe(true);
    expect(getRenderableMessageParts([textPart])).toEqual([textPart]);
  });

  test('renders assistant messages that only have footer error information', () => {
    expect(
      shouldRenderMessageBubble({
        info: {
          role: 'assistant',
          error: {
            name: 'MessageAbortedError',
            data: { message: 'aborted' },
          },
          cost: 0,
          tokens: {
            input: 0,
            output: 0,
            reasoning: 0,
            cache: { read: 0, write: 0 },
          },
        },
        parts: [] as Part[],
      }),
    ).toBe(true);
  });
});

describe('assistant response controls', () => {
  test('renders copy action and provider/model attribution below assistant response', () => {
    const previousProviders = useChatStore.getState().providers;
    useChatStore.setState({
      providers: [
        {
          id: 'anthropic',
          name: 'Anthropic',
          models: {
            'claude-sonnet-4-5': {
              id: 'claude-sonnet-4-5',
              name: 'Claude Sonnet 4.5',
            },
          },
        } as unknown as Provider,
      ],
    });

    try {
      const entry = {
        info: {
          id: 'msg-assistant',
          role: 'assistant',
          providerID: 'anthropic',
          modelID: 'claude-sonnet-4-5',
        },
        parts: [
          {
            id: 'part-text',
            sessionID: 'session',
            messageID: 'msg-assistant',
            type: 'text',
            text: 'First line.\n\nSecond line.',
          },
        ],
      } as unknown as OpencodeThreadEntry;

      const html = renderToStaticMarkup(createElement(MessageBubble, { entry }));

      expect(html).toContain('First line.');
      expect(html).toContain('Copy assistant response');
      expect(html).toContain('Generated by');
      expect(html).toContain('Anthropic');
      expect(html).toContain('Claude Sonnet 4.5');
      expect(html.indexOf('Copy assistant response')).toBeGreaterThan(html.indexOf('First line.'));
      expect(html.indexOf('Generated by')).toBeGreaterThan(html.indexOf('First line.'));
    } finally {
      useChatStore.setState({ providers: previousProviders });
    }
  });
});
